paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Fizz Buzz
      description: |
        [Challenge](https://leetcode.com/problems/fizz-buzz/)
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              numbers: array[number] | number
            examples:
              'Example 1':
                value: |
                  numbers: 3
              'Example 2':
                value: |
                  numbers: 5
              'Example 3':
                value: |
                  numbers: 15
              'Example 4':
                value: |
                  numbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                deletions: number
              examples:
                'Example 1':
                  value: |
                    deletions: 2 
                'Example 2':
                  value: |
                    deletions: 3
                'Example 3':
                  value: |
                    deletions: 4