description: |
  A boto3 wrapper for interacting with AWS services by defining
  requests and parameters as strings within YAML.
dependencies:
- name: boto3
  version: 
resources:
- title: Boto3
  url: boto3.amazonaws.com
environment:
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_REGION_NAME: ${AWS_REGION_NAME}
  S3_BUCKET: ${S3_BUCKET}
  ENV: local
  WORKDIR: ${WORKDIR}
