paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Word Break
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              string: string
              word_dict: array[string]
            examples:
              'Example 1':
                value: |
                  string: leetcode
                  word_dict: [leet, code]
              'Example 2':
                value: |
                  word_dict: [apple, pen]
                  string: applepenapple
              'Example 3':
                value: |
                  word_dict: [cats, dog, sand, and, cat]
                  string: catsandog
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                segments: array
              examples:
                'Example 1':
                  value: |
                    segments: [leet, code]
                'Example 2':
                  value: |
                    segments: [apple, pen, apple]
                'Example 3':
                  value: |
                    segments: []
components:
  examples:
    '{path}.description': |
      [Challenge](https://leetcode.com/problems/word-break/)