environment:
  DEBUG: True
resources:
- title: Best Time to Buy and Sell Stock
  url: https://www.google.com/amp/s/www.geeksforgeeks.org/best-time-to-buy-and-sell-stock/amp/
- function_name: main
  description: | 
    Orchestration function that executes the other functions within the module
  inputs:
    values:
    - prices: [7, 1, 5, 3, 6, 4]
  outputs:
    cast_as: dict
  expected_outputs:
  - max_possible_profit:
    - days: [1, 4]
      prices: [1, 6]
      profit: 5
  assertions: has_keys
- function_name: max_possible_profit
  description: |
    Returns a list of days to buy and sell stock that produce the maximum
    profit for a given list of stock prices over n days
  inputs:
    values:
    - prices: [7, 1, 5, 3, 6, 4]
    cast_as: Data
  outputs: 
    cast_as: dict
  expected_outputs:
  - - days: [1, 4]
      prices: [1, 6]
      profit: 5
  assertions:
- function_name: check_profit_and_store_stock
  description: | 
    Checks stock buy/sell profit and stores the stock if the profit exceeds
    previous profits
  inputs:
    values:
    - stock: 
        days: [0, 1]
        prices: [0, 1]
        profit: 1
      max_possible_profit: []
    - stock: 
        days: [1, 2]
        prices: [1, 2]
        profit: 1
      max_possible_profit: 
      - days: [0, 1]
        prices: [0, 1]
        profit: 1
    - stock: 
        days: [1, 3]
        prices: [1, 3]
        profit: 2
      max_possible_profit: 
      - days: [0, 1]
        prices: [0, 1]
        profit: 1
    cast_as: Dict
  outputs:
    cast_as: dict
  expected_outputs:
  - - days: [0, 1]
      prices: [0, 1]
      profit: 1
  - - days: [0, 1]
      prices: [0, 1]
      profit: 1
    - days: [1, 2]
      prices: [1, 2]
      profit: 1
  - - days: [1, 3]
      prices: [1, 3]
      profit: 2
  - max_possible_profit: [null]
  assertions: equals