paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Best Time to Buy and Sell Stock
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              prices: array
            examples:
              'Example 1':
                value: |
                  prices: [7, 1, 5, 3, 6, 4]
              'Example 2':
                value: |
                  prices: [7, 6, 4, 3, 1]
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                profit: number
              examples:
                'Example 1':
                  value: |
                    profit: 5
                'Example 2':
                  value: |
                    profit: 0
components:
  examples:
    '{path}.description': |
      [Challenge](https://www.google.com/amp/s/www.geeksforgeeks.org/best-time-to-buy-and-sell-stock/amp/)