description: Gets functions and inputs in modules located in a specified 
  directory. Modules should have the file name `app.py`, function names should
  be prefixed with `calculate_`, and inputs should be dataclass named `Data`
links: 
  - https://linuxhint.com/sys-path-append-python/
  - https://stackoverflow.com/questions/582056/getting-list-of-parameter-names-inside-python-function
  - https://www.geeksforgeeks.org/how-to-import-a-python-module-given-the-full-path/
environment:
  ROOT_DIRECTORY: ${PWD}
tests:
  # TODO - Testing Framework: Folders with data or scripts to use for testing
  # Folder name will be `[module_name]_test` and located in the same directory
  - name:  get_parent_directory
    input_dataclass: Data
    inputs: 
      - file_path: path_1/app_1.py 
      - file_path: path_2/app_2.py 
      - file_path: path_3/app_3.py
    outputs:
      - path_1
      - path_2
      - path_3
  - name:  get_operations_directory
    input_dataclass: Data
    inputs: 
      - file_path: path_1/app_1.py 
        directory_name: functions_1
      - file_path: path_2/app_2.py  
        directory_name: functions_2
      - file_path: path_3/app_3.py 
        directory_name: functions_3
    # TODO: Testing Framework: Only use supplied fields of dataclass when
    # to verify output
    outputs:
      - path_1/functions_1
      - path_2/functions_2
      - path_3/functions_3
  - name:  get_module_paths
    test_folder: test
    input_dataclass: Data
    inputs: 
      - operations_directory_path: '{CURRRENT_WORKING_DIRECTORY}/test/operations_1'
      - operations_directory_path: '{CURRRENT_WORKING_DIRECTORY}/test/operations_2'
    outputs:
      - module_paths: ['{CURRRENT_WORKING_DIRECTORY}/test/operations_1/add/app.py']
      - module_paths: []
  - name:  get_operations_from_paths
    input_dataclass: Data
    inputs: 
      - module_paths: ['{CURRRENT_WORKING_DIRECTORY}/test/operations_1/add/app.py']
      - module_paths: []
    outputs:
      - {'add.calculate_add': Operation(function=<function calculate_add at 0x7fa8c406e5f0>, data=<class 'app.Data'>)}
      - {}
  - name:  main
    input_dataclass: Data
    inputs: 
      - file_path: '{CURRRENT_WORKING_DIRECTORY}/test/operations_1/add/app.py'
        operations_directory_name: test/operations_1
      - file_path: '{CURRRENT_WORKING_DIRECTORY}/test/operations_1/add/app.py'
        operations_directory_name: test/operations_2
    outputs:
      - {'add.calculate_add': Operation(function=<function calculate_add at 0x7fa8c406e5f0>, data=<class 'app.Data'>)}
      - {}