paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Top Frequent k Words
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              grid: array[string]
              k: number
            examples:
              'Example 1':
                value: |
                  words: [i, love, leetcode, i, love, coding]
                  k: 2
              'Example 2':
                value: |
                  words: [the, day, is, sunny, the, the, the, sunny, is, is] 
                  k: 4
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                top_k_words: array
                count: number
              examples:
                'Example 1':
                  value: |
                    top_k_words: [i, love]
                    count: 2
                'Example 2':
                  value: |
                    count: 4
                    top_k_words: [the]
components:
  examples:
    '{path}.description': |
      [Challenge](https://leetcode.com/problems/top-k-frequent-words/)