paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Symmetric Tree
      description: |
        [Challenge](https://leetcode.com/problems/symmetric-tree/)
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              digits: string
            examples:
              'Example 1':
                value: |
                  root: [1,2,2,3,4,4,3]
              'Example 2':
                value: |
                  root: [1,2,2,null,3,null,3]
              'Example 3':
                value: |
                  root: [1]
              'Example 4':
                value: |
                  root: [1,2]
              'Example 5':
                value: |
                  root: [1,2,2]
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                output: bool
              examples:
                'Example 1':
                  value: |
                    output: false
                'Example 2':
                  value: |
                    output: true
                'Example 3':
                  value: |
                    output: true
                'Example 4':
                  value: |
                    output: false
                'Example 5':
                  value: |
                    output: true

                  