resources:
- title: Minimum Difficulty of a Job Schedule
  url: https://leetcode.com/problems/minimum-difficulty-of-a-job-schedule/
environment:
  DEBUG: True
tests:
- function_name:  pre_processing
  description: |
    Sets up the data object to facilitate proccessing 
    downstream
  inputs_values:
  - job_difficulty: []
  - job_difficulty: [1]
  - job_difficulty: [1, 2, 3]
  - job_difficulty: [1, 2, 3, 4]
  inputs_cast_as: Data
  expected_values:
  - jobs_n: 0
  - jobs_n: 1
  - jobs_n: 3
  - jobs_n: 4
  assertions: has_values
- function_name: get_jobs_by_day
  description: |
    Place jobs on the day(s) needed for to get the mimium
    difficultly
  inputs_cast_as: Data
  inputs_values:
  - days: 2
    job_difficulty: [1, 2, 3, 4, 5, 6]
  - days: 1
    job_difficulty: [1, 2, 3, 4, 5, 6]
  - days: 3
    job_difficulty: [1, 2, 3, 4, 5, 6]
  expected_outputs:
  - 0: [1]
    1: [2, 3, 4, 5, 6]
  - 0: [1, 2, 3, 4, 5, 6]
  - 0: [1]
    1: [2]
    2: [3, 4, 5, 6]
  assertions:
- function_name: get_minimum_difficulty
  description: |
    Gets the max value for each list of integers
    in a dictionaries list of values, and returns the 
    sum of the max values
  inputs_values:
  - jobs_by_days: {0: [1, 2, 3], 1: [4, 5]}
  - jobs_by_days: {0: [1, 2], 1: [4]}
  - jobs_by_days: {0: [1], 1: [4]}
  expected_outputs:
  - 8
  - 6
  - 5
  assertions: equals
- function_name: main
  description: |
    Orchestration function that executes the other
    functions within the module
  inputs_values:
  - job_difficulty: [6, 5, 4, 3, 2, 1]
    days: 2
  - job_difficulty: [9, 9, 9]
    days: 4
  - job_difficulty: [1, 1, 1]
    days: 3
  expected_outputs:
  - minimum_difficulty: 7
  - minimum_difficulty: -1
  - minimum_difficulty: 3
  assertions: [has_values]
