paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Meeting Rooms II
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              grid: array[array[number]]
            examples:
              'Example 1':
                value: |
                  meeting_times: [[0, 30],[5, 10],[15, 20]]
              'Example 2':
                value: |
                  meeting_times: [[0, 30], [5, 45], [15, 20]]
              'Example 3':
                value: |
                  meeting_times: [[7,10],[2,4]]
      responses:
        200:
          description: Successful Response
          content: 
            text/plain:
              schema:
                type: string
                $ref: '#/components/schemas/OK/text_plain'
              examples:
                'Example 1':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        meeting_times: [[0, 30],[5, 10],[15, 20]]
                      output: 
                        rooms: 2
                'Example 2':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        meeting_times: [[0, 30], [5, 45], [15, 20]]
                      output: 
                        rooms: 3
                'Example 3':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        meeting_times: [[7,10],[2,4]]
                      output: 
                        rooms: 1
components:
  examples:
    '{path}.description': |
      [Challenge](https://leetcode.ca/all/253.html)