paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Find Numbers with Even Digits
      description: |
        [Challenge](https://leetcode.com/problems/find-numbers-with-even-number-of-digits/)
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              nums: array[number]
            examples:
              'Example 1':
                value: |
                  nums: [12,345,2,6,7896]
              'Example 2':
                value: |
                  nums: [555,901,482,1771]
              'Example 3':
                value: |
                  digits: 2
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                even_digit_nums: array
                count: number
              examples:
                'Example 1':
                  value: |
                    even_digit_nums: [12, 7896]
                    count: 2
                'Example 2':
                  value: |
                    even_digit_nums: [1771]
                    count: 1
