paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Best Team with No Conflicts
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              scores: List[number]
              ages: List[number]
            examples:
              'Example 1':
                value: |
                  scores: [1, 3, 5, 10, 15]
                  ages: [1, 2, 3, 4, 5]
              'Example 2':
                value: |
                  scores: [4, 5, 6, 5]
                  ages: [2, 1, 2, 1]
              'Example 3':
                value: |
                  scores: [1, 2, 3, 5]
                  ages: [8, 9, 10, 1]
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                total_score: number
              examples:
                'Example 1':
                  value: |
                    total_score: 34
                'Example 2':
                  value: |
                   total_score: 15
                'Example 3':
                  value: |
                    total_score: 6
components:
  examples:
    '{path}.description': |
      [Challenge](https://leetcode.com/problems/best-team-with-no-conflicts/)