paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Alternating Chars
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              string: string
            examples:
              'Example 1':
                value: |
                  string: AABAAB
              'Example 2':
                value: |
                  string: AAAA
              'Example 3':
                value: |
                  string: BBBBB
              'Example 4':
                value: |
                  string: ABABABAB
              'Example 5':
                value: |
                  string: BABABA
              'Example 6':
                value: |
                  string: AAABBB
                  
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                deletions: number
              examples:
                'Example 1':
                  value: |
                    deletions: 2 
                'Example 2':
                  value: |
                    deletions: 3
                'Example 3':
                  value: |
                    deletions: 4
                'Example 4':
                  value: |
                    deletions: 0
                'Example 5':
                  value: |
                    deletions: 0
                'Example 6':
                  value: |
                    deletions: 4
components:
  examples:
    '{path}.description': |
      [Challenge](https://www.hackerrank.com/challenges/alternating-characters/problem)