paths: 
  '/{path}/':
    get:
      tags:
      - Examples
      summary: Hello World      
      description:
        $ref: '#/components/examples/{path}.description'
      parameters:
      - in: query
        name: name
        type: string
        examples: 
          World:
            value: World
          Mars:
            value: Mars
      responses:
        200:
          description: Success
          content:
            'text/html':
              schema:
                type: string
                example: <html>Example HTML Response</html>
    post:
      tags:
      - Examples
      summary: Hello World
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          application/json:
            schema: 
              type: object
            examples: 
              'Earth':
                value: 
                  name: Earth
          text/plain:
            schema:
              type: string
            examples:
              'Mars':
                value: |
                  name: Mars
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                data: string
              examples:
                'Mars': 
                  value: |
                    data: Hello Mars!
            application/json:
              schema:
                type: object
                properties:
                  data: 
                    type: string
              examples:
                'Earth':
                  data: 'Hello Earth!'

components:
  examples:
    '{path}.description': |
      The GET route serves an HTML page that displays the greeting
      **Hello World**. The greeting is generated when the page
      loads and sends a POST request to the same URL. If the 
      query parameter `name` is included in the URL, the generated
      greeting is **Hello [name]**.