paths: 
  '/{path}/':
    post:
      tags:
      - Algorithms
      summary: Linked Lists
      description: |
        Functions for working with linked lists:
        * Convert a list of items to a linked list
        * Convert a linked list to a list of items
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              values: array[any] | null
            examples:
              'Array to linked list - Example 1':
                value: |
                  values: [1, 2, 3 ,4, 5]
              'Array to linked list - Example 2':
                value: |
                  values: []
              'Array to linked list - Example 3':
                value: |
                  values: ['value']
              'Array to linked list - Example 4':
                value: |
                  values: ['head', 'node_1', 'node_2']
              'Linked list to array - Example 5':
                value: |
                  linked_list:
                    head:
                      next_node:
                        next_node:
                          next_node:
                            next_node:
                              next_node: null
                              value: 5
                            value: 4
                          value: 3
                        value: 2
                      value: 1
              'Linked list to array - Example 6':
                value: |
                  linked_list:
                    head: null
              'Linked list to array - Example 7':
                value: |
                  linked_list:
                    head:
                      next_node: null
                      value: value
              'Linked list to array - Example 8':
                value: |
                  linked_list:
                    head:
                      next_node:
                        next_node:
                          next_node: null
                          value: node_2
                        value: node_1
                      value: head
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                linked_list: object
                values: array
              examples:
                'Array to linked list - Example 1':
                  value: |
                    linked_list:
                      head:
                        next_node:
                          next_node:
                            next_node:
                              next_node:
                                next_node: null
                                value: 5
                              value: 4
                            value: 3
                          value: 2
                        value: 1
                'Array to linked list - Example 2':
                  value: |
                    linked_list:
                      head: None
                'Array to linked list - Example 3':
                  value: |
                    linked_list:
                      head:
                        next_node: null
                        value: value
                'Array to linked list - Example 4':
                  value: |
                    linked_list:
                      head:
                        next_node:
                          next_node:
                            next_node: null
                            value: node_2
                          value: node_1
                        value: head
                'Linked list to array - Example 5':
                  value: |
                    values:
                    - 1
                    - 2
                    - 3
                    - 4
                    - 5
                'Linked list to array - Example 6':
                  value: |
                    values: []
                'Linked list to array - Example 7':
                  value: |
                    values:
                    - value
                'Linked list to array - Example 8':
                  value: |
                    values:
                    - head
                    - node_1
                    - node_2