paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: 3 Sum
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              nums: List[string]
            examples:
              'Example 1':
                value: |
                  nums: [-1, 0, 1, 2, -1, -4]
              'Example 2':
                value: |
                  nums: [0, 1, 1]
              'Example 3':
                value: |
                  nums: [0, 0, 0]
      responses:
        200:
          description: Successful Response
          content: 
            text/plain:
              schema:
                $ref: '#/components/schemas/OK/text_plain'
              examples:
                'Example 1':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      nums: [-1, 0, 1, 2, -1, -4]
                      triplets:
                      - [-1, -1, 2]
                      - [-1, 0, 1]
                'Example 2':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      nums: [0, 1, 1]
                      triplets: []
                'Example 3':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      nums: [0, 0, 0]
                      triplets: 
                      - [0, 0, 0]
components:
  examples:
    '{path}.description': |
      [Challenge](https://leetcode.com/problems/3sum/)