environment:
  DEBUG: False
tests:
- function_name: main
  description: >
    Orchestrates the execution of the other functions within the 
    module
  inputs_values:
  - n: 3
    k: 3
  - n: 4
    k: 9
  - n: 3
    k: 1
  expected_outputs:
  - output: '213'
  - output: '2314'
  - output: '123'
  assertions: has_values
- function_name: get_chars
  description: >
    Returns a list of numbers, 1 to n, to use for permutations
  inputs_values:
  - chars: null
    n: 3
  - chars: null
    n: 4
  - chars: null
    n: 5
  - chars: ['1', '2', '3', '4']
    n: 0
  expected_outputs:
  - ['1', '2', '3']
  - ['1', '2', '3', '4']
  - ['1', '2', '3', '4', '5']
  - ['1', '2', '3', '4']
  assertions: equals
- function_name: get_permutations
  description: >
    Returns a list of all of the permutations of a group of chars
    as dot delimited strings
  inputs:
    values:
    - chars: ['1', '2']
    - chars: ['1', '2', '3']
    - chars: ['1', '2', '3', '4']
  expected_outputs:
  - ['1.2', '2.1']
  - - 1.2.3
    - 1.3.2
    - 2.1.3
    - 2.3.1
    - 3.1.2
    - 3.2.1
  - - 1.2.3.4
    - 1.2.4.3
    - 1.3.2.4
    - 1.3.4.2
    - 1.4.2.3
    - 1.4.3.2
    - 2.1.3.4
    - 2.1.4.3
    - 2.3.1.4
    - 2.3.4.1
    - 2.4.1.3
    - 2.4.3.1
    - 3.1.2.4
    - 3.1.4.2
    - 3.2.1.4
    - 3.2.4.1
    - 3.4.1.2
    - 3.4.2.1
    - 4.1.2.3
    - 4.1.3.2
    - 4.2.1.3
    - 4.2.3.1
    - 4.3.1.2
    - 4.3.2.1
  assertions: equals
- function_name: process_permutations
  description: > 
    Returns the kth permutation of the chars, sans dots, if it
    exists
  inputs_values:
  - permutations: ['1.2', '2.1']
    n: 2
  - permutations:
    - 1.2.3
    - 1.3.2
    - 2.1.3
    - 2.3.1
    - 3.1.2
    - 3.2.1
    n: 3
  - permutations:
    - 1.2.3.4
    - 1.2.4.3
    - 1.3.2.4
    - 1.3.4.2
    - 1.4.2.3
    - 1.4.3.2
    - 2.1.3.4
    - 2.1.4.3
    - 2.3.1.4
    - 2.3.4.1
    - 2.4.1.3
    - 2.4.3.1
    - 3.1.2.4
    - 3.1.4.2
    - 3.2.1.4
    - 3.2.4.1
    - 3.4.1.2
    - 3.4.2.1
    - 4.1.2.3
    - 4.1.3.2
    - 4.2.1.3
    - 4.2.3.1
    - 4.3.1.2
    - 4.3.2.1
    n: 9
  expected_outputs:
  - '21'
  - '213'
  - '2314'
  assertions: equals