functions:
  - name: get_linked_list_from_list_of_values
    description: Returns a linked list form a list of values
    tests:
      inputs:
      - items: [1]
      - items: [1, 2]
      - items: [a, b, c]
      - items: [1, 2, 3, 4]
      cast_outputs_as: dict
      outputs:
      - head: {next: null, value: 1}
      - head:
          next: {next: null, value: 2}
          value: 1
      - head:
          next:
            next: {next: null, value: c}
            value: b
          value: a
      - head:
          next:
            next:
              next: {next: null, value: 1}
              value: 2
            value: 3
          value: 4
  - name: get_list_of_values_from_linked_list
    description: Converts a linked list of nodes to a list of items
    tests:
      cast_inputs_as: Linked_List
      inputs:
      - in_reverse: False
        linked_list:
          head:
            value: 1
            next: null
      - in_reverse: False
        linked_list:
          head:
            value: 1
            next: 
              value: 2
              next: null
      - in_reverse: False
        linked_list:
          head:
            value: a
            next: 
              value: b
              next: 
                value: c
                next: null
      - in_reverse: True
        linked_list:
          head:
            value: 1
            next: null
      - in_reverse: True
        linked_list:
          head:
            value: 1
            next: 
              value: 2
              next: null
      - in_reverse: True
        linked_list:
          head:
            value: a
            next: 
              value: b
              next: 
                value: c
                next: null
      outputs: 
      - [1]
      - [1, 2]
      - [a, b, c]
      - [1]
      - [2, 1]
      - [c, b, a]
  - name: main
    tests:
      - description: Converts a list of values to a linked list. Returns the 
          linked list in reverse
        cast_inputs_as: Data
        inputs:
          - items: [1]
          - items: [1, 2]
          - items: [a, b, c]
          - items: [1, 2, 3, 4]
        # TODO: Testing framework - cast outputs to type before any asserts
        # outputs_cast_to: str
        cast_outputs_as: dict
        outputs:
        - items: [1]
          reversed_linked_list:
            head: {next: null, value: 1}
          reversed_items: [1]
          linked_list:
            head: {next: null, value: 1}
        - items: [1, 2]
          reversed_linked_list:
            head:
              next: {next: null, value: 2}
              value: 1
          reversed_items: [2, 1]
          linked_list:
            head:
              next: {next: null, value: 1}
              value: 2
        - items: [a, b, c]
          reversed_linked_list:
            head:
              next:
                next: {next: null, value: c}
                value: b
              value: a
          reversed_items: [c, b, a]
          linked_list:
            head:
              next:
                next: {next: null, value: a}
                value: b
              value: c
        - items: [1, 2, 3, 4]
          reversed_linked_list:
            head:
              next:
                next:
                  next: {next: null, value: 4}
                  value: 3
                value: 2
              value: 1
          reversed_items: [4, 3, 2, 1]
          linked_list:
            head:
              next:
                next:
                  next: {next: null, value: 1}
                  value: 2
                value: 3
              value: 4