paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Trapping Rain Water
      description: |
        [Challenge](https://leetcode.com/problems/trapping-rain-water/)
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              height: array[number]
            examples:
              'Example 1':
                value: |
                  height: [0,1,0,2,1,0,1,3,2,1,2,1]
              'Example 2':
                value: |
                  height: [4,2,0,3,2,5]
              'Example 3':
                value: |
                  height: [1, 3, 2, 4, 1, 3, 1, 4, 5, 2, 2, 1, 4, 2, 2]
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                total: number
                trapped_rain: array
              examples:
                'Example 1':
                  value: |
                    total: 6
                    trapped_rain: [1, 1, 2, 1, 0, 1]
                'Example 2':
                  value: |
                    total: 9
                    trapped_rain: [2, 4, 1, 2]
                'Example 3':
                  value: |
                    total: 15
                    trapped_rain: [1, 3, 1, 3, 0, 2, 2, 3]
