description: |
  Challenge #2 [Easy]
  Hello, coders! An important part of programming is being able to apply your 
  programs, so your challenge for today is to create a calculator application 
  that has use in your life. It might be an interest calculator, or it might be 
  something that you can use in the classroom. For example, if you were in 
  physics class, you might want to make a F = M * A calc.

  EXTRA CREDIT: make the calculator have multiple functions! Not only should it 
  be able to calculate F = M * A, but also A = F/M, and M = F/A!
links: 
  - https://www.reddit.com/r/dailyprogrammer/comments/pjbj8/easy_challenge_2/
  - https://linuxhint.com/sys-path-append-python/
  - https://stackoverflow.com/questions/582056/getting-list-of-parameter-names-inside-python-function
  - https://www.geeksforgeeks.org/how-to-import-a-python-module-given-the-full-path/
  - https://stackoverflow.com/questions/1187970/how-to-exit-from-python-without-traceback
tests: