paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Sales by Match
      description: |
        [Challenge](https://www.hackerrank.com/challenges/sock-merchant/problem)
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              socks: array
            examples:
              'Example 1':
                value: |
                  socks: [1, 2, 1, 2, 1, 3, 2]
              'Example 2':
                value: |
                  socks: [10, 20, 20, 10, 10, 30, 50, 10, 20]
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                matching_pairs: object
                count: number
              examples:
                'Example 1':
                  value: |
                    matching_pairs:
                      1: 1
                      2: 1
                    count: 2
                'Example 2':
                  value: |
                    matching_pairs:
                      10: 2
                      20: 1
                    n: 3
                          