paths: 
  '/{path}/':
    post:
      tags:
      - TODO
      - Games
      summary: Benchmark Sudoku Solver
      description: |
        Benchmark the Sudoku solver using the puzzles found 
        [here](https://codegolf.stackexchange.com/questions/190727/the-fastest-sudoku-solver).
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              grid: array[number | string] | object | str | null
            examples:
              '2*2 Grid':
                value: |
                  grid:
                  - [0, 0]
                  - [0, 1]https://codegolf.stackexchange.com/questions/190727/the-fastest-sudoku-solver
              '3*3 Grid':
                value: |
                  grid:
                  - [0,0,0]
                  - [1,0,3]
                  - [0,0,0]
              '9*9 Grid - Invalid':
                value: |
                  grid:
                  - [9,6,2,0,3,5,8,0,9]
                  - [0,0,5,0,0,6,0,0,0]
                  - [4,0,0,0,8,0,2,0,6]
                  - [0,0,0,7,4,9,1,3,0]
                  - [0,9,0,3,0,0,7,6,0]
                  - [0,0,3,0,0,0,5,0,8]
                  - [0,2,0,8,6,7,9,1,5]
                  - [0,0,6,0,0,3,0,0,0]
                  - [1,7,0,5,0,0,0,8,0]
              '9*9 Grid':
                value: |
                  grid:
                  - [9,6,2,0,3,5,8,0,0]
                  - [0,0,5,0,0,6,0,0,9]
                  - [4,0,0,0,8,0,2,0,6]
                  - [0,0,0,7,4,9,1,3,0]
                  - [0,9,0,3,0,0,7,6,0]
                  - [0,0,3,0,0,0,5,0,8]
                  - [0,2,0,8,6,7,9,1,5]
                  - [0,0,6,0,0,3,0,0,0]
                  - [1,7,0,5,0,0,0,8,0]
              '9*9 Grid - Hard':
                value: |
                  grid:
                  - [0,0,0,0,2,0,4,0,0]
                  - [9,0,6,0,8,0,0,0,0]
                  - [0,0,0,0,0,3,0,0,6]
                  - [0,0,0,0,0,0,7,5,4]
                  - [3,8,0,0,0,0,0,2,0]
                  - [1,0,0,0,0,0,0,3,0]
                  - [0,5,0,4,0,0,0,0,2]
                  - [0,7,0,0,0,0,0,0,0]
                  - [0,0,3,5,0,7,0,0,0]
              '9*9 Grid - Expert':
                value: |
                  grid:
                  - [0, 0, 0, 0, 0, 0, 0, 1, 0]
                  - [4, 0, 0, 0, 0, 0, 0, 0, 0]
                  - [0, 2, 0, 0, 0, 0, 0, 0, 0]
                  - [0, 0, 0, 0, 5, 0, 4, 0, 7]
                  - [0, 0, 8, 0, 0, 0, 3, 0, 0]
                  - [0, 0, 1, 0, 9, 0, 0, 0, 0]
                  - [3, 0, 0, 4, 0, 0, 2, 0, 0]
                  - [0, 5, 0, 1, 0, 0, 0, 0, 0]
                  - [0, 0, 0, 8, 0, 6, 1, 0, 0]
      responses:
        200:
          description: Successful Response
          content: 
            text/plain:
              schema:
                type: string
                $ref: '#/components/schemas/OK/text_plain'
              examples:
                '2*2 grid':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      data:
                        grid:
                        - [0, 0]
                        - [0, 1]
                        solution:
                        - [1, 2]
                        - [2, 1]
                '3*3 grid':
                  value: |
                    code: 200
                    status: OK
                    data:
                      grid:
                      - [0, 0, 0]
                      - [1, 0, 3]
                      - [0, 0, 0]
                      solution:
                      - [3, 1, 2]
                      - [1, 2, 3]
                      - [2, 3, 1]
                '9*9 Grid - Invalid':
                  value: |
                    code: 200
                    status: OK
                    data:
                      grid:
                      - [9, 6, 2, 0, 3, 5, 8, 0, 9]
                      - [0, 0, 5, 0, 0, 6, 0, 0, 0]
                      - [4, 0, 0, 0, 8, 0, 2, 0, 6]
                      - [0, 0, 0, 7, 4, 9, 1, 3, 0]
                      - [0, 9, 0, 3, 0, 0, 7, 6, 0]
                      - [0, 0, 3, 0, 0, 0, 5, 0, 8]
                      - [0, 2, 0, 8, 6, 7, 9, 1, 5]
                      - [0, 0, 6, 0, 0, 3, 0, 0, 0]
                      - [1, 7, 0, 5, 0, 0, 0, 8, 0]
                      solution: null
                '9*9 Grid':
                  value: |
                    code: 200
                    status: OK
                    data:
                      grid:
                      - [9, 6, 2, 0, 3, 5, 8, 0, 0]
                      - [0, 0, 5, 0, 0, 6, 0, 0, 9]
                      - [4, 0, 0, 0, 8, 0, 2, 0, 6]
                      - [0, 0, 0, 7, 4, 9, 1, 3, 0]
                      - [0, 9, 0, 3, 0, 0, 7, 6, 0]
                      - [0, 0, 3, 0, 0, 0, 5, 0, 8]
                      - [0, 2, 0, 8, 6, 7, 9, 1, 5]
                      - [0, 0, 6, 0, 0, 3, 0, 0, 0]
                      - [1, 7, 0, 5, 0, 0, 0, 8, 0]
                      solution:
                      - [9, 6, 2, 4, 3, 5, 8, 7, 1]
                      - [8, 4, 5, 1, 7, 6, 3, 2, 9]
                      - [4, 3, 7, 9, 8, 1, 2, 5, 6]
                      - [6, 5, 8, 7, 4, 9, 1, 3, 2]
                      - [2, 9, 1, 3, 5, 8, 7, 6, 4]
                      - [7, 1, 3, 6, 9, 2, 5, 4, 8]
                      - [3, 2, 4, 8, 6, 7, 9, 1, 5]
                      - [5, 8, 6, 2, 1, 3, 4, 9, 7]
                      - [1, 7, 9, 5, 2, 4, 6, 8, 3]
                '9*9 Grid - Hard':
                  value: |
                    code: 200
                    status: OK
                    data:
                      grid:
                      - [0, 0, 0, 0, 2, 0, 4, 0, 0]
                      - [9, 0, 6, 0, 8, 0, 0, 0, 0]
                      - [0, 0, 0, 0, 0, 3, 0, 0, 6]
                      - [0, 0, 0, 0, 0, 0, 7, 5, 4]
                      - [3, 8, 0, 0, 0, 0, 0, 2, 0]
                      - [1, 0, 0, 0, 0, 0, 0, 3, 0]
                      - [0, 5, 0, 4, 0, 0, 0, 0, 2]
                      - [0, 7, 0, 0, 0, 0, 0, 0, 0]
                      - [0, 0, 3, 5, 0, 7, 0, 0, 0]
                      solution:
                      - [6, 3, 5, 8, 2, 1, 4, 9, 7]
                      - [9, 1, 6, 2, 8, 4, 3, 7, 5]
                      - [5, 4, 2, 1, 7, 3, 9, 8, 6]
                      - [8, 6, 9, 3, 1, 2, 7, 5, 4]
                      - [3, 8, 7, 9, 4, 5, 6, 2, 1]
                      - [1, 9, 4, 7, 5, 6, 2, 3, 8]
                      - [7, 5, 8, 4, 3, 9, 1, 6, 2]
                      - [2, 7, 1, 6, 9, 8, 5, 4, 3]
                      - [4, 2, 3, 5, 6, 7, 8, 1, 9]
                '9*9 Grid - Expert':
                  value: |
                    code: 200
                    status: OK