paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Reverse Nodes in k-Group
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              head: array[number]
              k: number
            examples:
              'Example 1':
                value: |
                  head: [1, 2, 3, 4, 5]
                  k: 2
              'Example 2':
                value: |
                  head: [1, 2, 3, 4, 5]
                  k: 3
      responses:
        200:
          description: Successful Response
          content: 
            text/plain:
              schema:
                type: string
                $ref: '#/components/schemas/OK/text_plain'
              examples:
                'Example 1':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        grid:
                        - [2, 1, 1]
                        - [1, 1, 0]
                        - [0, 1, 1]
                      output: 
                        minutes: 4
                'Example 1':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        head: [1, 2, 3, 4, 5]
                        k: 2
                      output:
                        reversed_nodes: [2, 1, 4, 3, 5]
                'Example 2':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        head: [1, 2, 3, 4, 5]
                        k: 3
                      output:
                        reversed_nodes: [3, 2, 1, 4, 5]
components:
  examples:
    '{path}.description': |
      [Challenge](https://leetcode.com/problems/reverse-nodes-in-k-group/)