paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Word Search
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              board: array[array[string]]
              words: array[string]
            examples:
              'Example 1':
                value: |
                  board:
                  - [A, B, C, E]
                  - [S, F, C, S]
                  - [A, D, E, E] 
                  word: ABCCED
              'Example 2':
                value: |
                  board:
                  - [A, B, C, E]
                  - [S, F, C, S]
                  - [A, D, E, E] 
                  word: ABZCCED
      responses:
        200:
          description: Successful Response
          content: 
            text/plain:
              schema:
                type: string
                $ref: '#/components/schemas/OK/text_plain'
              examples:
                'Example 1':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        board:
                        - [A, B, C, E]
                        - [S, F, C, S]
                        - [A, D, E, E] 
                        word: ABCCED
                      output:
                        paths: [0.0|0.1|0.2|1.2|2.2|2.1]
                'Example 2':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        board:
                        - [A, B, C, E]
                        - [S, F, C, S]
                        - [A, D, E, E] 
                        word: ABZCCED
                      output: 
                        paths: []
components:
  examples:
    '{path}.description': |
      [Challenge](https://leetcode.com/problems/word-search/)