paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Word Square
      description: |
        [Challenge](https://leetcode.ca/all/425.html)
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              sequence: array[string]
            examples:
              'Example 1':
                value: |
                  sequence: [area, lead, wall, lady, ball]
              'Example 2':
                value: |
                  sequence: [abat, baba, atan, atal]
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                word_squares: array
                count: number
              examples:
                'Example 1':
                  value: |
                    word_squares:
                    - - wall
                      - area
                      - lead
                      - lady
                    - - ball
                      - area
                      - lead
                      - lady
                    count: 2
                'Example 2':
                  value: |
                    word_squares:
                    - - baba
                      - abat
                      - baba
                      - atan
                    - - baba
                      - abat
                      - baba
                      - atal
                    count: 2