paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Reorganize String
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              string: string
            examples:
              'Example 1':
                value: |
                  string: aab
              'Example 2':
                value: |
                  string: aaab
              'Example 3':
                value: |
                  string: abc
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                reorganizes_string: string
              examples:
                'Example 1':
                  value: |
                    reorganizes_string: aba
                'Example 2':
                  value: |
                    reorganized_string: ''
                'Example 3':
                  value: |
                    reorganized_string: cba
components:
  examples:
    '{path}.description': |
      [Challenge](https://leetcode.com/problems/reorganize-string/)
