paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Number of Islands
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              grid: array[array[number]]
            examples:
              'Example 1':
                value: |
                  grid:
                  - [1,1,1,1,0]
                  - [1,1,0,1,0]
                  - [1,1,0,0,0]
                  - [0,0,0,0,0]
              'Example 2':
                value: |
                  grid:
                  - [1,1,0,0,0]
                  - [1,1,0,0,0]
                  - [0,0,1,0,0]
                  - [0,0,0,1,1]
      responses:
        200:
          description: Successful Response
          content: 
            text/plain:
              schema:
                type: string
                $ref: '#/components/schemas/OK/text_plain'
              examples:
                'Example 1':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        grid:
                        - [1,1,1,1,0]
                        - [1,1,0,1,0]
                        - [1,1,0,0,0]
                        - [0,0,0,0,0]
                      output: 
                        islands: 
                          n: 1
                          values: 
                          - ['0.0', '0.1', '1.0', '0.2', '1.1', '0.3', '1.3', '2.1', '2.0']
                'Example 2':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        grid:
                        - [1,1,0,0,0]
                        - [1,1,0,0,0]
                        - [0,0,1,0,0]
                        - [0,0,0,1,1]
                      output: 
                        islands: 
                          n: 3
                          values: 
                          - ['0.0', '0.1', '1.0', '1.1]
                          - ['2.2']
                          - ['3.3', '3.4']
components:
  examples:
    '{path}.description': |
      [Challenge](https://leetcode.com/problems/number-of-islands/)