paths: 
  '/{path}/':
    post:
      tags:
      - TODO
      - Coding Challenges
      summary: Longest Sub Sequence
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              nums: List[string]
            examples:
              'Example 1':
                value: |
                  nums: [-1, 0, 1, 2, -1, -4]
              'Example 2':
                value: |
                  nums: [0, 1, 1]
              'Example 3':
                value: |
                  nums: [0, 0, 0]
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                triplets: array
              examples:
                'Example 1':
                  value: |
                    triplets:
                    - [-1, -1, 2]
                    - [-1, 0, 1]
                'Example 2':
                  value: |
                    triplets: []
                'Example 3':
                  value: |
                    triplets: 
                    - [0, 0, 0]
components:
  examples:
    '{path}.description': |
      [Challenge](https://leetcode.com/problems/3sum/)