paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Mark and Toys
      description: |
        [Challenge](https://www.hackerrank.com/challenges/mark-and-toys/problem)
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              prices: array[number]
              budget: number
            examples:
              'Example 1':
                value: |
                  prices: [1, 12, 5, 111, 200, 1000, 10]
                  budget: 50
              'Example 2':
                value: |
                  prices: [1, 2, 3, 4]
                  budget: 7
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                max_price: number
                prices: array
              examples:
                'Example 1':
                  value: |
                    max_price: 28
                    prices: [1.5.10.12]
                'Example 2':
                  value: |
                    max_price: 10
                    prices: [1.2.3.4] 