paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Merge Two Sorted Linked Lists
      description: |
        [Challenge](https://leetcode.com/problems/merge-two-sorted-lists/)
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              list1: array[number]
              list2: array[number]
            examples:
              'Example 1':
                value: |
                  list1: [1, 2, 4]
                  list2: [1, 3, 4]
              'Example 2':
                value: |
                  list1: []
                  list2: []
              'Example 3':
                value: |
                  list1: []
                  list2: [0]
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                merged_list: array
              examples:
                'Example 1':
                  value: |
                    merged_list: [1, 1, 2, 3, 4, 4]
                'Example 2':
                  value: |
                    merged_list: []
                'Example 3':
                  value: |
                    merged_list = []
components:
  examples:
    '{path}.description': |
      [Challenge](https://leetcode.com/problems/letter-combinations-of-a-phone-number/)