paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Custom Sorted Array
      description: |
        [Challenge](https://leetcode.com/discuss/interview-question/916854/custom-sorted-array-with-even-numbers-at-beginning-and-odd-at-end-of-the-array/)
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              numbers: array[number]
            examples:
              'Example 0':
                value: |
                  numbers: [6,3,4,5]
              'Example 1':
                value: |
                  numbers: [13,10,21,20]
              'Example 2':
                value: |
                  numbers: [8,5,11,4,6]
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                moves: array
                count: number
              examples:
                'Example 0':
                  value: |
                    moves:
                    count: 1
                'Example 1':
                  value: |
                    moves:
                    count: 3
                'Example 2':
                  value: |
                    moves:
                    count: 3
