paths: 
  '/{path}/':
    get:
      tags:
      - TODO
      - Calculator
      summary: Calculator     
      description:
        $ref: '#/components/examples/{path}.description'
      # parameters:
      # - in: query
      #   name: name
      #   type: string
      #   examples: 
      #     World:
      #       value: World
      #     Mars:
      #       value: Mars
      responses:
        200:
          description: Successful Response
          content:
            'text/html':
              schema:
                type: string
                example: <html>Example HTML Response</html>
    post:
      tags:
      - TODO
      - Coding Challenges
      summary: Calculator
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              digits: string
            examples:
              'List Operations':
                value: |
                  operations:
                  - name: null
              'Example 1':
                value: |
                  operations:
                  - name: add
                    a: 0
                    b: 1
                  - name: subtract
                    ans: true
                    a: [1, 2, 3]
              'Example 2':
                value: |
                  operations:
                    name: absolute_value
                    a: 0
              'Example 3':
                value: |
                  digits: 2
      responses:
        200:
          description: Successful Response
          content: 
            text/plain:
              schema:
                type: string
                $ref: '#/components/schemas/OK/text_plain'
              examples:
                'Example 1':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        digits: 23
                      output: [AD, AE, AF, BD, BE, BF, CD, CE, CF]
                'Example 2':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        digits: ''
                      output: []
                'Example 3':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        digits: 2
                      output: [A, B, C]
components:
  examples:
    '{path}.description': |
      [Challenge](https://leetcode.com/problems/letter-combinations-of-a-phone-number/)