resources:
- title: Minimum Swaps 2
  url: https://www.hackerrank.com/challenges/minimum-swaps-2/problem
tests:
- function_name: main
  description: Should return the minimum number of swaps needed
    to sort the list
  inputs:
    values:
    - array: [1,2,3,4]
    - array: [7,1,3,2,4,5,6]
    - array: [2,3,4,1,5]
    - array: [4,3,1,2]
  expected_outputs: 
  - 0
  - 5
  - 3
  - 3
- function_name: swap_positions
  description:
  inputs: 
    values:
    - array: [1, 2, 3, 4]
      max_difference_position: 0
      min_difference_position: 0
    - array: [1, 2, 3, 4]
      max_difference_position: 1
      min_difference_position: 2
    - array: [1, 2, 3, 4]
      max_difference_position: 3
      min_difference_position: 0
    - array: [1, 2, 3, 4]
      max_difference_position: 2
      min_difference_position: 3
  expected_outputs: 
  - array: [1, 2, 3, 4]
    differences: []
    max_difference_position: 0
    min_difference_position: 0
    swap_count: 0
  - array: [1, 3, 2, 4]
    differences: []
    max_difference_position: 0
    min_difference_position: 0
    swap_count: 0
  - array: [4, 2, 3, 1]
    differences: []
    max_difference_position: 0
    min_difference_position: 0
  - array: [1, 2, 4, 4]
    differences: []
    max_difference_position: 0
    min_difference_position: 0
    swap_count: 0
- function_name: get_positions_to_swap
  description:
  inputs:
    values:
    - array: [1, 2, 3, 4]
    - array: [4, 3, 1, 2]
    - array: [1, 2, 4, 3]
    - array: [1, 2, 4, 4]
  expected_outputs:
  - array: [1, 2, 3, 4]
    differences: [1, 1, 1, 1]
    max_difference_position: 3
    min_difference_position: 3
    swap_count: 0
  - array: [4, 2, -1, -1]
    differences: [4, 1, -3, -2]
    max_difference_position: 0
    min_difference_position: 2
    swap_count: 0
  - array: [1, 2, 4, 3]
    differences: [1, 1, 2,0]
    max_difference_position: 2
    min_difference_position: 3
    swap_count: 0
  - array: [7, 1, 3, 2, 4, 5, 6]
    differences: [7, 0, 1, -1, 0, 0, 0]
    max_difference_position: 0
    min_difference_position: 3
    swap_count: 0