paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Minimum Swaps II
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              array: array[number]
            examples:
              'Example 0':
                value: |
                  array: [7, 1, 3, 2, 4, 5, 6]
              'Example 1':
                value: |
                  array: [4, 3, 1, 2]
              'Example 2':
                value: |
                  array: [2, 3, 4, 1, 5]
              'Example 3':
                value: |
                  array: [1, 3, 5, 2, 4, 6, 7]
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                swaps: number
              examples:
                'Example 0':
                  value: |
                    swaps: 5
                'Example 1':
                  value: |
                    swaps: 3
                'Example 2':
                  value: |
                    swaps: 3
                'Example 3':
                  value: |
                    swaps: 8
components:
  examples:
    '{path}.description': |
      [Challenge](https://www.hackerrank.com/challenges/minimum-swaps-2/problem)