paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Remove Vowels from String
      description: |
        [Challenge](https://leetcode.com/problems/reorganize-string/)
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              string: string
            examples:
              'Example 1':
                value: |
                  string: test
              'Example 2':
                value: |
                  string: hello
              'Example 3':
                value: |
                  string: world
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                modified_string: string
              examples:
                'Example 1':
                  value: |
                    modified_string: tst
                'Example 2':
                  value: |
                    modified_string: hll
                'Example 3':
                  value: |
                    modified_string: wrld
