paths: 
  '/{path}/':
    post:
      tags:
      - Algorithms
      summary: Partition Matrix into Edges
      description: |
        This splits a rectangle into edges. 
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              shape: array
            examples:
              '1 x 1 matrix':
                value: |
                  shape: [1, 1]
              '3 x 1 matrix':
                value: |
                  shape: 4, 1]
              '4 x 4 matrix':
                value: |
                  shape: [4, 4]
              '4 x 4 matrix':
                value: |
                  shape: [5, 5]
              '5 x 5 matrix':
                value: |
                  shape: [3, 3]
              '4 x 3 matrix':
                value: |
                  shape: [4, 3]
              '5 x 4 matrix':
                value: |
                  shape: [5, 4]
              '6 x 5 matrix':
                value: |
                  shape: [6, 5]
      responses:
        200:
          description: Success
          content: 
            application/json:
              schema:
                type: string
                response: object
              examples:
              '1 x 1 matrix':
                value:
                - - [0, 0]
                  - [0, 0]
                - - [0, 0]
                  - [0, 0]
                - - [0, 0]
                  - [0, 0]
              '3 x 1 matrix':
                value:
                - - [1, 0]
                  - [2, 0]
                - - [0, 0]
                  - [1, 0]
                - - [1, 0]
                  - [3, 0]
              '4 x 4 matrix':
                value:
                - - [1, 1]
                  - [1, 1]
                - - [1, 2]
                  - [1, 2]
                - - [2, 1]
                  - [2, 1]
                - - [2, 2]
                  - [2, 2]
                - - [0, 0]
                  - [0, 1]
                - - [0, 0]
                  - [1, 0]
                - - [0, 2]
                  - [0, 3]
                - - [0, 3]
                  - [1, 3]
                - - [2, 0]
                  - [3, 0]
                - - [3, 0]
                  - [3, 1]
                - - [3, 2]
                  - [3, 3]
                - - [2, 3]
                  - [3, 3]
              '4 x 4 matrix':
                value:
                - - [2, 2]
                  - [2, 2]
                - - [1, 1]
                  - [1, 3]
                - - [1, 1]
                  - [3, 1]
                - - [1, 3]
                  - [3, 3]
                - - [3, 1]
                  - [3, 3]
                - - [0, 0]
                  - [0, 4]
                - - [0, 0]
                  - [4, 0]
                - - [0, 4]
                  - [4, 4]
                - - [4, 0]
                  - [4, 4]
              '5 x 5 matrix':
                value:
                - - [1, 1]
                  - [1, 1]
                - - [0, 0]
                  - [0, 2]
                - - [0, 0]
                  - [2, 0]
                - - [0, 2]
                  - [2, 2]
                - - [2, 0]
                  - [2, 2]
              '4 x 3 matrix':
                value:
                - - [2, 1]
                  - [2, 1]
                - - [0, 1]
                  - [0, 1]
                - - [1, 0]
                  - [1, 2]
                - - [1, 0]
                  - [3, 0]
                - - [1, 2]
                  - [3, 2]
                - - [3, 0]
                  - [3, 2]
                - - [0, 0]
                  - [0, 1]
                - - [0, 1]
                  - [2, 0]
              '5 x 4 matrix':
                value:
                - - [2, 1]
                  - [2, 1]
                - - [2, 2]
                  - [2, 2]
                - - [3, 1]
                  - [3, 1]
                - - [3, 2]
                  - [3, 2]
                - - [0, 1]
                  - [0, 2]
                - - [1, 0]
                  - [1, 1]
                - - [1, 0]
                  - [2, 0]
                - - [1, 2]
                  - [1, 3]
                - - [1, 3]
                  - [2, 3]
                - - [3, 0]
                  - [4, 0]
                - - [4, 0]
                  - [4, 1]
                - - [4, 2]
                  - [4, 3]
                - - [3, 3]
                  - [4, 3]
                - - [0, 0]
                  - [0, 1]
                - - [0, 1]
                  - [3, 0]
              '6 x 5 matrix':
                value:
                - - [3, 2]
                  - [3, 2]
                - - [0, 2]
                  - [0, 2]
                - - [2, 1]
                  - [2, 3]
                - - [2, 1]
                  - [4, 1]
                - - [2, 3]
                  - [4, 3]
                - - [4, 1]
                  - [4, 3]
                - - [1, 0]
                  - [1, 4]
                - - [1, 0]
                  - [5, 0]
                - - [1, 4]
                  - [5, 4]
                - - [5, 0]
                  - [5, 4]
                - - [0, 0]
                  - [0, 2]
                - - [0, 2]
                  - [4, 0]
        500:
          description: Internal Server Error
          content: 
            application/json:
              schema:
                type: string
                detail:
                  Code: string
                  Message: string
              examples:
                value:
                  detail: 'Internal server error'
              
        