
functions:
  - name: get_odds_count
    description: 
    inputs:
    - a: 0
      b: 0
    - a: 0
      b: 1
    - a: 1
      b: 1
    - a: 2
      b: 2
    - a: -1
      b: 3
    - a: 7
      b: 3
    - a: 10
      b: 8
    - a: 10
      b: 9
    - a: 11
      b: 8
    - a: 11
      b: 0
    - a: 10
      b: 0
    outputs:
    - 0
    - 1
    - 1
    - 0
    - 3
    - 3
    - 1
    - 1
    - 2
    - 6
    - 5
  - name: case_one_number_are_nonzero
    description: Returns the count of odds numbers between two non-zero integers
    inputs:
    - a: 1
      b: 1
    - a: 2
      b: 2
    - a: 1
      b: 2
    - a: 1
      b: 3
    - a: -1
      b: -3
    - a: 1
      b: 5
    outputs:
    - 1
    - 0
    - 1
    - 2
    - 3
    - 3
  - name: case_one_number_is_zero
    description: Returns the ceiling or floor of a non-zero, even or odd number 
      divided by two for the case where only one number is non-zero
    inputs:
    - a: 1
      b: 0
    - a: -2
      b: 0
    - a: 3
      b: 0
    - a: 4
      b: 0
    outputs:
    - 1
    - 1
    - 2
    - 2
  - name: case_both_numbers_are_zero
    description: Returns `zero` for the case of both integers being 0
    inputs:
    - a: null
      b: null
    - a: 0
      b: 0
    - a: 1
      b: 1
    outputs:
    - 0
    - 0
    - 0
  - name:  main
    description: Returns the odd numbers between two numbers
    inputs: 
    - interval: [0, 0]
    - interval: [0, 1]
    - interval: [1, 1]
    - interval: [2, 2]
    - interval: [-1, 3]
    - interval: [7, 3]
    - interval: [10, 8]
    - interval: [10, 9]
    - interval: [11, 8]
    - interval: [11, 0]
    - interval: [10, 0]
    outputs:
    - interval: [0, 0]
      odds_count: 0
    - interval: [0, 1]
      odds_count: 1
    - interval: [1, 1]
      odds_count: 1
    - interval: [2, 2]
      odds_count: 0
    - interval: [-1, 3]
      odds_count: 3
    - interval: [7, 3]
      odds_count: 3
    - interval: [10, 8]
      odds_count: 1
    - interval: [10, 9]
      odds_count: 1
    - interval: [11, 8]
      odds_count: 2
    - interval: [11, 0]
      odds_count: 6
    - interval: [10, 0]
      odds_count: 5
