paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Critical Connections
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              n: number
              connections: array[array[number]]
            examples:
              'Example 1':
                value: |
                  n: 4 
                  connections: 
                  - [0,1]
                  - [1,2]
                  - [2,0]
                  - [1,3]
              'Example 2':
                value: |
                  n: 2
                  connections: 
                  - [0,1]
              'Example 3':
                value: |
                  n: 6
                  connections: 
                  - [0, 1]
                  - [1, 2]
                  - [2, 0]
                  - [1, 3]
                  - [3, 4]
                  - [3, 5]
              'Example 4':
                value: |
                  n: 6
                  connections: 
                  - [0,1]
                  - [1,2]
                  - [2,0]
                  - [3,5]
                  - [3,4]
                  - [4,5]
      responses:
        200:
          description: Successful Response
          content: 
            text/plain:
              schema:
                type: string
                $ref: '#/components/schemas/OK/text_plain'
              examples:
                'Example 1':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input: 
                        n: 4 
                        connections: 
                        - [0,1]
                        - [1,2]
                        - [2,0]
                        - [1,3]
                      output:
                      - [1,3]
                'Example 2':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input: 
                        n: 2
                        connections: 
                        - [0,1]
                      output: 
                      - [0,1]
                'Example 3':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input: 
                        n: 6
                        connections: 
                        - [0, 1]
                        - [1, 2]
                        - [2, 0]
                        - [1, 3]
                        - [3, 4]
                        - [3, 5]
                      output: 
                      - [1, 3]
                'Example 4':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input: 
                        n: 6
                        connections: 
                        - [0,1]
                        - [1,2]
                        - [2,0]
                        - [3,5]
                        - [3,4]
                        - [4,5]
                      output: 
                      - []
components:
  examples:
    '{path}.description': |
      [Challenge](https://leetcode.com/problems/critical-connections-in-a-network/)