environment:
  DEBUG: False
resources:
- title: Verifying an alien dictionary
  url: https://leetcode.com/problems/verifying-an-alien-dictionary/
tests:
- function_name: main
  description: |
    Orchestrates the execution the other functions within the
    module. Returns true if a list of words is in lexicographical,
    otherwise false.
  inputs_values:
  - words: 
    - world
    - worlds
    - row
    order: worldabcefghijkmnpqstuvxyz
  - words: 
    - hello
    - leetcode
    order: hlabcdefgijkmnopqrstuvwxyz
  expected_outputs:
  - false
  - true
  assertions: equals
- function_name: get_word_combinations
  description: |
    Returns combinations of length two, of the 
    words passed in
  inputs_values:
  - words: [a, b]
  - words: [a, b, c]
  - words: [a, b, c, d]
  expected_outputs:
  - [a, b]
  - [[a, b], [a, c], [b, c]]
  - [[a, b], [a, c], [a, d], [b, c], [b, d], [c, d]]
  assertions: equals
- function_name: check_char_order
  description: |
  inputs_values:
  - - [0, 1, 2, 3]
    - [0, 1, 2, 3]
  - - [0, 1, 2, 3]
    - [1, 2, 3, 4]
  expected_outputs:
  - true
  - false
  assertions: equals
- function_name: get_char_orders
  description: |
    Returns the order of chars for two words
  inputs_values:
  - words: 
    - abc
    - abcd
    order: dcba
    - abca
    - abcd
    order: abcd
  expected_outputs:
  - - [3, 2, 1, -1]
    - [3, 2, 1, 0]
  - - [0, 1, 2, 0]
    - [0, 1, 2, 3]
  assertions: equals
s