paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Verifying an Alien Dictionary
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              order: string
              words: array[string]
            examples:
              'Example 1':
                value: |
                  words: 
                  - world
                  - worlds
                  - row
                  order: worldabcefghijkmnpqstuvxyz
              'Example 2':
                value: |
                  words: 
                  - hello
                  - leetcode
                  order: hlabcdefgijkmnopqrstuvwxyz
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                output: bool
              examples:
                'Example 1':
                  value: |
                    output: false
                'Example 2':
                  value: |
                    output: true
components:
  examples:
    '{path}.description': |
      [Challenge](https://leetcode.com/problems/verifying-an-alien-dictionary/)