paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Number of Provinces
      description: |
        [Challenge](https://leetcode.com/problems/number-of-provinces/)
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              cities: array[array[number]]
              exclude_diagonals: bool | null
            examples:
              'Example 1':
                value: |
                  cities: 
                  - [1, 0, 0]
                  - [0, 1, 0]
                  - [0, 0, 1]
                  exclude_diagonals: true
              'Example 2':
                value: |
                  cities: 
                  - [1, 0, 0]
                  - [0, 1, 0]
                  - [0, 0, 1]
                  exclude_diagonals: false
              'Example 3':
                value: |
                  cities:
                  - [1, 1, 0]
                  - [1, 1, 0]
                  - [0, 0, 1]
              'Example 4':
                value: |
                  cities:
                  - [1, 1, 0]
                  - [1, 1, 0]
                  - [0, 0, 1]
                  exclude_diagonals: true
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                provinces: array
                count: number
              examples:
                'Example 1':
                  value: |
                    count: 3
                    provinces:
                    - []
                    - ['0.0']
                    - ['1.1']
                    - ['2.2']
                'Example 2':
                  value: |
                    count: 1
                    provinces:
                    - []
                    - ['0.0', '1.1', '2.2']
                'Example 3':
                  value: |
                    count: 1
                    provinces:
                    - []
                    - ['0.0', '0.1', '1.0', '1.1', '2.2']
                'Example 4':
                  value: |
                    count: 2
                    provinces:
                    - []
                    - ['0.0', '0.1', '1.0', '1.1']
                    - ['2.2']