functions:
- function_name:
  description:
  inputs_values:
  expected_outputs:
  assertions:
- function_name: get_steps
  description: |
    Returns the number of squares that can be made by stepping from
    the starting position to an ending position. 
    Example:
    - start: 0.0 
      end: 0.0
      step: 1
    - start: 0.0 
      end: 1.1 
      step: 2
    - start: 0.0
      end: 2.2
      step: 3
  inputs_values:
  - matrix_m: 4
    matrix_n: 5
    max_dimension: 5
    position:
    - 0
    - 0
  expected_outputs:
  - - 1
    - 2
    - 3
    - 4
  assertions: equals
- function_name: get_squares_for_position
  description: Returns all of the squares that can be formed start from a position  in the matrix
  inputs_values:
  - matrix_m: 4
    matrix_n: 5
    position:
    - 0
    - 0
    steps:
    - 1
    - 2
    - 3
    - 4
  expected_outputs:
  - - - '0.0'
    - - '0.0'
      - '0.1'
      - '1.0'
      - '1.1'
    - - '0.0'
      - '0.1'
      - '0.2'
      - '1.0'
      - '1.1'
      - '1.2'
      - '2.0'
      - '2.1'
      - '2.2'
    - - '0.0'
      - '0.1'
      - '0.2'
      - '0.3'
      - '1.0'
      - '1.1'
      - '1.2'
      - '1.3'
      - '2.0'
      - '2.1'
      - '2.2'
      - '2.3'
      - '3.0'
      - '3.1'
      - '3.2'
      - '3.3'
  assertions: equals
- function_name: pre_processing
  description: Formatting data to facilitate processing downstream. Adding position
    values and squares to the data object
  inputs_values:
  - matrix:
    - - 1
      - 0
      - 1
      - 0
      - 0
    - - 1
      - 0
      - 1
      - 1
      - 1
    - - 1
      - 1
      - 1
      - 1
      - 1
    - - 1
      - 0
      - 0
      - 1
      - 0
  inputs_cast_as: Data
  expected_outputs:
  - positions:
      '0.0': 1
      '0.1': 0
      '0.2': 1
      '0.3': 0
      '0.4': 0
      '1.0': 1
      '1.1': 0
      '1.2': 1
      '1.3': 1
      '1.4': 1
      '2.0': 1
      '2.1': 1
      '2.2': 1
      '2.3': 1
      '2.4': 1
      '3.0': 1
      '3.1': 0
      '3.2': 0
      '3.3': 1
      '3.4': 0
    squares:
      '0.0':
      - - '0.0'
      - - '0.0'
        - '0.1'
        - '1.0'
        - '1.1'
      - - '0.0'
        - '0.1'
        - '0.2'
        - '1.0'
        - '1.1'
        - '1.2'
        - '2.0'
        - '2.1'
        - '2.2'
      - - '0.0'
        - '0.1'
        - '0.2'
        - '0.3'
        - '1.0'
        - '1.1'
        - '1.2'
        - '1.3'
        - '2.0'
        - '2.1'
        - '2.2'
        - '2.3'
        - '3.0'
        - '3.1'
        - '3.2'
        - '3.3'
      '0.1':
      - - '0.1'
      - - '0.1'
        - '0.2'
        - '1.1'
        - '1.2'
      - - '0.1'
        - '0.2'
        - '0.3'
        - '1.1'
        - '1.2'
        - '1.3'
        - '2.1'
        - '2.2'
        - '2.3'
      - - '0.1'
        - '0.2'
        - '0.3'
        - '0.4'
        - '1.1'
        - '1.2'
        - '1.3'
        - '1.4'
        - '2.1'
        - '2.2'
        - '2.3'
        - '2.4'
        - '3.1'
        - '3.2'
        - '3.3'
        - '3.4'
      '0.2':
      - - '0.2'
      - - '0.2'
        - '0.3'
        - '1.2'
        - '1.3'
      - - '0.2'
        - '0.3'
        - '0.4'
        - '1.2'
        - '1.3'
        - '1.4'
        - '2.2'
        - '2.3'
        - '2.4'
      '0.3':
      - - '0.3'
      - - '0.3'
        - '0.4'
        - '1.3'
        - '1.4'
      '0.4':
      - - '0.4'
      '1.0':
      - - '1.0'
      - - '1.0'
        - '1.1'
        - '2.0'
        - '2.1'
      - - '1.0'
        - '1.1'
        - '1.2'
        - '2.0'
        - '2.1'
        - '2.2'
        - '3.0'
        - '3.1'
        - '3.2'
      '1.1':
      - - '1.1'
      - - '1.1'
        - '1.2'
        - '2.1'
        - '2.2'
      - - '1.1'
        - '1.2'
        - '1.3'
        - '2.1'
        - '2.2'
        - '2.3'
        - '3.1'
        - '3.2'
        - '3.3'
      '1.2':
      - - '1.2'
      - - '1.2'
        - '1.3'
        - '2.2'
        - '2.3'
      - - '1.2'
        - '1.3'
        - '1.4'
        - '2.2'
        - '2.3'
        - '2.4'
        - '3.2'
        - '3.3'
        - '3.4'
      '1.3':
      - - '1.3'
      - - '1.3'
        - '1.4'
        - '2.3'
        - '2.4'
      '1.4':
      - - '1.4'
      '2.0':
      - - '2.0'
      - - '2.0'
        - '2.1'
        - '3.0'
        - '3.1'
      '2.1':
      - - '2.1'
      - - '2.1'
        - '2.2'
        - '3.1'
        - '3.2'
      '2.2':
      - - '2.2'
      - - '2.2'
        - '2.3'
        - '3.2'
        - '3.3'
      '2.3':
      - - '2.3'
      - - '2.3'
        - '2.4'
        - '3.3'
        - '3.4'
      '2.4':
      - - '2.4'
      '3.0':
      - - '3.0'
      '3.1':
      - - '3.1'
      '3.2':
      - - '3.2'
      '3.3':
      - - '3.3'
      '3.4':
      - - '3.4'
  assertions: has_values
- function_name: process_squares
  description: Processes squares and returns the squares filled with ones in a dictionary, where the keys of the dictionary are the number of positions
    in the squares
  inputs_values:
  - positions:
      '0.0': 1
      '0.1': 0
      '0.2': 1
      '0.3': 0
      '0.4': 0
      '1.0': 1
      '1.1': 0
      '1.2': 1
      '1.3': 1
      '1.4': 1
      '2.0': 1
      '2.1': 1
      '2.2': 1
      '2.3': 1
      '2.4': 1
      '3.0': 1
      '3.1': 0
      '3.2': 0
      '3.3': 1
      '3.4': 0
    squares:
      '0.0':
      - - '0.0'
      - - '0.0'
        - '0.1'
        - '1.0'
        - '1.1'
      - - '0.0'
        - '0.1'
        - '0.2'
        - '1.0'
        - '1.1'
        - '1.2'
        - '2.0'
        - '2.1'
        - '2.2'
      - - '0.0'
        - '0.1'
        - '0.2'
        - '0.3'
        - '1.0'
        - '1.1'
        - '1.2'
        - '1.3'
        - '2.0'
        - '2.1'
        - '2.2'
        - '2.3'
        - '3.0'
        - '3.1'
        - '3.2'
        - '3.3'
      '0.1':
      - - '0.1'
      - - '0.1'
        - '0.2'
        - '1.1'
        - '1.2'
      - - '0.1'
        - '0.2'
        - '0.3'
        - '1.1'
        - '1.2'
        - '1.3'
        - '2.1'
        - '2.2'
        - '2.3'
      - - '0.1'
        - '0.2'
        - '0.3'
        - '0.4'
        - '1.1'
        - '1.2'
        - '1.3'
        - '1.4'
        - '2.1'
        - '2.2'
        - '2.3'
        - '2.4'
        - '3.1'
        - '3.2'
        - '3.3'
        - '3.4'
      '0.2':
      - - '0.2'
      - - '0.2'
        - '0.3'
        - '1.2'
        - '1.3'
      - - '0.2'
        - '0.3'
        - '0.4'
        - '1.2'
        - '1.3'
        - '1.4'
        - '2.2'
        - '2.3'
        - '2.4'
      '0.3':
      - - '0.3'
      - - '0.3'
        - '0.4'
        - '1.3'
        - '1.4'
      '0.4':
      - - '0.4'
      '1.0':
      - - '1.0'
      - - '1.0'
        - '1.1'
        - '2.0'
        - '2.1'
      - - '1.0'
        - '1.1'
        - '1.2'
        - '2.0'
        - '2.1'
        - '2.2'
        - '3.0'
        - '3.1'
        - '3.2'
      '1.1':
      - - '1.1'
      - - '1.1'
        - '1.2'
        - '2.1'
        - '2.2'
      - - '1.1'
        - '1.2'
        - '1.3'
        - '2.1'
        - '2.2'
        - '2.3'
        - '3.1'
        - '3.2'
        - '3.3'
      '1.2':
      - - '1.2'
      - - '1.2'
        - '1.3'
        - '2.2'
        - '2.3'
      - - '1.2'
        - '1.3'
        - '1.4'
        - '2.2'
        - '2.3'
        - '2.4'
        - '3.2'
        - '3.3'
        - '3.4'
      '1.3':
      - - '1.3'
      - - '1.3'
        - '1.4'
        - '2.3'
        - '2.4'
      '1.4':
      - - '1.4'
      '2.0':
      - - '2.0'
      - - '2.0'
        - '2.1'
        - '3.0'
        - '3.1'
      '2.1':
      - - '2.1'
      - - '2.1'
        - '2.2'
        - '3.1'
        - '3.2'
      '2.2':
      - - '2.2'
      - - '2.2'
        - '2.3'
        - '3.2'
        - '3.3'
      '2.3':
      - - '2.3'
      - - '2.3'
        - '2.4'
        - '3.3'
        - '3.4'
      '2.4':
      - - '2.4'
      '3.0':
      - - '3.0'
      '3.1':
      - - '3.1'
      '3.2':
      - - '3.2'
      '3.3':
      - - '3.3'
      '3.4':
      - - '3.4'
  expected_outputs:
    0.0:
    - - '0.0'
      - '0.1'
      - '1.0'
      - '1.1'
    - - '0.0'
      - '0.1'
      - '0.2'
      - '1.0'
      - '1.1'
      - '1.2'
      - '2.0'
      - '2.1'
      - '2.2'
    - - '0.0'
      - '0.1'
      - '0.2'
      - '0.3'
      - '1.0'
      - '1.1'
      - '1.2'
      - '1.3'
      - '2.0'
      - '2.1'
      - '2.2'
      - '2.3'
      - '3.0'
      - '3.1'
      - '3.2'
      - '3.3'
    - - '0.1'
    - - '0.1'
      - '0.2'
      - '1.1'
      - '1.2'
    - - '0.1'
      - '0.2'
      - '0.3'
      - '1.1'
      - '1.2'
      - '1.3'
      - '2.1'
      - '2.2'
      - '2.3'
    - - '0.1'
      - '0.2'
      - '0.3'
      - '0.4'
      - '1.1'
      - '1.2'
      - '1.3'
      - '1.4'
      - '2.1'
      - '2.2'
      - '2.3'
      - '2.4'
      - '3.1'
      - '3.2'
      - '3.3'
      - '3.4'
    - - '0.2'
      - '0.3'
      - '1.2'
      - '1.3'
    - - '0.2'
      - '0.3'
      - '0.4'
      - '1.2'
      - '1.3'
      - '1.4'
      - '2.2'
      - '2.3'
      - '2.4'
    - - '0.3'
    - - '0.3'
      - '0.4'
      - '1.3'
      - '1.4'
    - - '0.4'
    - - '1.0'
      - '1.1'
      - '2.0'
      - '2.1'
    - - '1.0'
      - '1.1'
      - '1.2'
      - '2.0'
      - '2.1'
      - '2.2'
      - '3.0'
      - '3.1'
      - '3.2'
    - - '1.1'
    - - '1.1'
      - '1.2'
      - '2.1'
      - '2.2'
    - - '1.1'
      - '1.2'
      - '1.3'
      - '2.1'
      - '2.2'
      - '2.3'
      - '3.1'
      - '3.2'
      - '3.3'
    - - '1.2'
      - '1.3'
      - '1.4'
      - '2.2'
      - '2.3'
      - '2.4'
      - '3.2'
      - '3.3'
      - '3.4'
    - - '2.0'
      - '2.1'
      - '3.0'
      - '3.1'
    - - '2.1'
      - '2.2'
      - '3.1'
      - '3.2'
    - - '2.2'
      - '2.3'
      - '3.2'
      - '3.3'
    - - '2.3'
      - '2.4'
      - '3.3'
      - '3.4'
    - - '3.1'
    - - '3.2'
    - - '3.4'
    1.0:
    - - '0.0'
    - - '0.2'
    - - '1.0'
    - - '1.2'
    - - '1.3'
    - - '1.4'
    - - '2.0'
    - - '2.1'
    - - '2.2'
    - - '2.3'
    - - '2.4'
    - - '3.0'
    - - '3.3'
    4.0:
    - - '1.2'
      - '1.3'
      - '2.2'
      - '2.3'
    - - '1.3'
      - '1.4'
      - '2.3'
      - '2.4'
  assertions: equals
- function_name: get_maximal_squares
  description: Returns the maximal squares, squares with the largest area, from
    a dictionary containing squares by area
  inputs_values: 
  - 1: squares_1
  - 0: squares_0
    1: squares_1
  - 0: squares_0
    1: squares_1
    2: squares_2
  expected_outputs:
  - 1: squares_1
  - 1: squares_1
  - 2: squares_2
  assertions: equals
- function_name: main
  description: Orchestrates the execution of functions within the module.
  inputs_values:
  - matrix: 
    - [1, 0, 1, 0, 0]
    - [1, 0, 1, 1, 1]
    - [1, 1, 1, 1, 1]
    - [1, 0, 0, 1, 0]
  inputs_cast_as: Data
  expected_outputs:
  - maximal_squares:
      4.0:
      - - '1.2'
        - '1.3'
        - '2.2'
        - '2.3'
      - - '1.3'
        - '1.4'
        - '2.3'
        - '2.4'
  assertions: has_values