paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Maximal Square
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              matrix: array[array[number]]
            examples:
              'Example 1':
                value: |
                  matrix: 
                  - [1, 0, 1, 0, 0]
                  - [1, 0, 1, 1, 1]
                  - [1, 1, 1, 1, 1]
                  - [1, 0, 0, 1, 0]
              'Example 2':
                value: |
                  matrix: 
                  - [0, 1]
                  - [1, 0]
              'Example 3':
                value: |
                  matrix: 
                  - [0]
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                largest_square: array
                count: number
              examples:
                'Example 1':
                  value: |
                    count: 4
                    largest_square: 
                    - - ['1.2', '1.3', '2.2', '2.3']
                      - ['1.3', '1.4', '2.3', '2.4']
                'Example 2':
                  value: |
                    count: 1
                    largest_square:
                    - - ['0.1']
                      - ['1.0']
                'Example 3':
                  value: |
                    count: 0
                    largest_square:
                    - - ['0.0']         
components:
  examples:
    '{path}.description': |
      [Challenge](https://leetcode.com/problems/maximal-square/)