paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Unique Paths III
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              grid: array[array[number]]
            examples:
              'Example 1':
                value: |
                  grid:
                  - [0, 1]
                  - [2, 0]
              'Example 2':
                value: |
                  grid:
                  - [1,0,0,0]
                  - [0,0,0,0]
                  - [0,0,0,2]
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                output: number
              examples:
                'Example 1':
                  value: |
                    output: 0
                'Example 2':
                  value: |
                    output: 4
components:
  examples:
    '{path}.description': |
      [Challenge](https://leetcode.com/problems/unique-paths-iii/)