paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Count Inversions
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              players: array[object]
            examples:
              'Example 1':
                value: |
                  array: [2, 4, 1]
              'Example 2':
                value: |
                  array: [1, 1, 1, 2, 2]
              'Example 3':
                value: |
                  array: [2, 1, 3, 1, 2]
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                inversions:
                  n: number
                  values: array
              examples:
                'Example 1':
                  value: |
                    inversions:
                      n: 2
                      values: 
                      - [4, 1]
                      - [2, 1]
                'Example 2':
                  value: |
                    inversions:
                      n: 0
                      values: []
                'Example 3':
                  value: |
                    inversions:
                      n: 4
                      values:
                      - 
                      - 
                      - 
                      - 
components:
  examples:
    '{path}.description': |
      [Challenge](https://www.hackerrank.com/challenges/ctci-merge-sort/problem)