paths: 
  '/{path}/':
    post:
      tags:
      - TODO
      - Coding Challenges
      summary: Letter Combinations of Phone Numbers
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              digits: string
            examples:
              'Example 1':
                value: |
                  digits: 23
              'Example 2':
                value: |
                  digits: ''
              'Example 3':
                value: |
                  digits: 2
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                output: array
              examples:
                'Example 1':
                  value: |
                    output: [AD, AE, AF, BD, BE, BF, CD, CE, CF]
                'Example 2':
                  value: |
                    output: []
                'Example 3':
                  value: |
                    output: [A, B, C]
components:
  examples:
    '{path}.description': |
      [Challenge](https://leetcode.com/problems/letter-combinations-of-a-phone-number/)