description: |
  Formats output data by:
  - removing key/values from a a dictionary
  - setting dataclass field values as null 
tests:
- function_name: case_data_is_dict
  description: Handles cases where the data to be formatted is a dictionary
  inputs: 
    values:
    - a: a
      b: b
      remove_fields: [remove_fields]
    - a: a
      b: b
      remove_fields: [a, remove_fields]
    - a: a
      b: b
      remove_fields: [b, remove_fields]
    - a: a
      b: b
      remove_fields: [a, b, remove_fields]
  expected_outputs:
  - a: a
    b: b
  - b: b
  - a: a
  - {}
  assertions: equals
- function_name: case_data_is_dataclass
  description: Handles cases where the data to be formatted is a dataclass
  inputs: 
    values:
    - a: a
      b: b
      remove_fields: [remove_fields]
    - a: a
      b: b
      remove_fields: [a, remove_fields]
    - a: a
      b: b
      remove_fields: [b, remove_fields]
    - a: a
      b: b
      remove_fields: [a, b, remove_fields]
    cast_as: test_resources_app.Data
  expected_outputs:
  - remove_fields: null
    b: b
  - a: null
    remove_fields: null
  - b: null
    remove_fields: null
  - a: null
    b: null
    remove_fields: null
  assertions: has_values
- function_name: main
  description: Orchestration function that executes the other functions within the module
  inputs:
    values:
    - a: a
      b: b
      remove_fields: [a, b, remove_fields]
    - a: a
      b: b
      remove_fields: [a, b, remove_fields]
    cast_as:
    - null
    - test_resources_app.Data
  expected_outputs:
  - {}
  - a: null
    b: null
    remove_fields: null
  assertions: 
  - equals
  - has_values