paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Word Search II
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              board: array[array[string]]
              words: array[string]
            examples:
              'Example 1':
                value: |
                  board:
                  - [o, a, a, n]
                  - [e, t, a, e]
                  - [i, h, k, r]
                  - [i, f, l, v]
                  words: [oath, pea, eat, rain]
              'Example 2':
                value: |
                  board:
                  - [a, b]
                  - [c, d]
                  words: [abcd]
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                words: array
              examples:
                'Example 1':
                  value: |
                    words: 
                      oath: ['0.0', '0.1', '1.1', '2.1']
                      pea: []
                      eat: ['1.3', '1.2', '1.1']
                      rain: []
                'Example 2':
                  value: |
                    words:
                      abcd: []
components:
  examples:
    '{path}.description': |
      [Challenge](https://leetcode.com/problems/word-search-ii/)