paths: 
  '/{path}/':
    post:
      tags:
      - Utilities
      summary: Web Scraper
      description: |

      requestBody:
        content:
          text/plain:
            schema:
              type: string
              nums: List[string]
            examples:
              'Example 1':
                value: |
                  ''
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                triplets: array
              examples:
                'Example 1':
                  value: |
                    ''
components:
  examples:
    '{path}.description': |
      [Challenge](https://leetcode.com/problems/3sum/)