paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Baseball Game
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              operations: List[AnyValue]
            examples:
              'Example 1':
                value: |
                  operations: [5, 2, C, D, +]
              'Example 2':
                value: |
                  operations: [5, -2, 4, C, D, 9, +, +]
              'Example 3':
                value: |
                  operations: [1, C]
      responses:
        200:
          description: Successful Response
          content: 
            text/plain:
              schema:
                $ref: '#/components/schemas/OK/text_plain'
              examples:
                'Example 1':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      inputs:
                        operations: [5, 2, C, D, +]
                      outputs:
                        total_score: 30
                'Example 2':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      inputs:
                        operations: [5, -2, 4, C, D, 9, +, +]
                      outputs:
                        total_score: 27
                'Example 3':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      inputs:
                        operations: [1, C]
                      ouptuts:
                        total_score: 0
components:
  examples:
    '{path}.description': |
      [Challenge](https://leetcode.com/problems/baseball-game/)