paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Matrix Color
      description: |
        [Challenge](http://www.youtube.com/watch?v=IWvbPIYQPFM)
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              matrix: array[array[string]]
            examples:
              'Example 1':
                value: |
                  matrix:
                  - [B, G, R]
                  - [B, B, G]
                  - [R, B, G]
                  - [R, R, B]
      responses:
        200:
          description: Successful Response
          content: 
            text/plain:
              schema:
                type: string
                $ref: '#/components/schemas/OK/text_plain'
              examples:
                'Example 1':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        digits: 23
                      output: 
                        connections:
                          values:
                          - ['0.0', '1.0', '1.1', '2.1', '3.2']
                          - ['0.1', '1.2', '2.2']
                          - ['0.2']
                          - ['2.0', '3.0', '3.1']
                          n: 4
