paths: 
  '/{path}/':
    post:
      tags:
      - TODO
      - Algorithms
      summary: Tokenization
      description: |
        Calculates the distance between two strings or two lists of strings, with
        or without preserving order.

        [Levenshtein Distance](https://en.wikipedia.org/wiki/Levenshtein_distance)
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              item_1: array[string] | string
              item_2: array[string] | string
              ordered: bool | null
            examples:
              'Example 1':
                value: |
                  item_1: item_1
                  item_2: item_2
              'Example 2':
                value: |
                  item_1: 'no'
                  item_2: bo
              'Example 3':
                value: |
                  item_1: 'on'
                  item_2: bo
                  preserve_order: true
              'Example 4':
                value: |
                  item_1: honda
                  item_2: hyundai
              'Example 5':
                value: |
                  item_1: [law, and, order]
                  item_2: [order, and, law]
                  preserve_order: true
              'Example 6':
                value: |
                  item_1: [law, and, order]
                  item_2: [order, and, law]
                  preserve_order: false

      responses:
        200:
          description: Successful Response
          content: 
            text/plain:
              schema:
                type: string
                $ref: '#/components/schemas/OK/text_plain'
              examples:
                'Example 1':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        item_1: item_1
                        item_2: item_2
                      output: 
                        difference: {modifications: 1, percentage: 0.17}
                'Example 2':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        item_1: 'no'
                        item_2: bo
                      output: 
                        difference: {modifications: 1, percentage: 0.5}
                'Example 3':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        item_1: 'on'
                        item_2: bo
                      output: 
                        difference: {modifications: 2, percentage: 1.0}
                'Example 4':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        item_1: item_1
                        item_2: item_2
                      output: 
                        difference: {modifications: 4, percentage: 0.57}
                'Example 5':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        item_1: [law, and, order]
                        item_2: [order, and, law]
                        ordered: true
                      output: 
                        difference: {modifications: 2, percentage: 0.67}
                'Example 6':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        item_1: [law, and, order]
                        item_2: [order, and, law]
                        ordered: false
                      output: 
                        difference: {modifications: 0, percentage: 0.0}
                        