paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Rotting Oranges
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              grid: array[array[number]]
            examples:
              'Example 1':
                value: |
                  grid:
                  - [2, 1, 1]
                  - [1, 1, 0]
                  - [0, 1, 1]
              'Example 2':
                value: |
                  grid:
                  - [2,1,1]
                  - [0,1,1]
                  - [1,0,1]
              'Example 3':
                value: |
                  grid:
                  - [0, 2]
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                minutes: number
              examples:
                'Example 1':
                  value: |
                    minutes: 4
                'Example 2':
                  value: |
                    minutes: -1
                'Example 3':
                  value: |
                    minutes: 0
components:
  examples:
    '{path}.description': |
      [Challenge](https://leetcode.com/problems/rotting-oranges/)