paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Letter Combinations of Phone Numbers
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              digits: string
            examples:
              'Example 1':
                value: |
                  digits: 23
              'Example 2':
                value: |
                  digits: ''
              'Example 3':
                value: |
                  digits: 2
      responses:
        200:
          description: Successful Response
          content: 
            text/plain:
              schema:
                type: string
                $ref: '#/components/schemas/OK/text_plain'
              examples:
                'Example 1':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        digits: 23
                      output: [AD, AE, AF, BD, BE, BF, CD, CE, CF]
                'Example 2':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        digits: ''
                      output: []
                'Example 3':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        digits: 2
                      output: [A, B, C]
components:
  examples:
    '{path}.description': |
      [Challenge](https://leetcode.com/problems/letter-combinations-of-a-phone-number/)