paths: 
  '/{path}/':
    post:
      tags:
      - TODO
      - Security
      summary: Authentication
      description: |
        Authenticates the users can access an endpoint. 
          - Returns the metadata associated with a user (id, roles, user agent, 
            origin, etc). 
          - Raises an error if the user cannot be authenticated. 
          - Creates an token for anonymous users when an endpoint allows anonymous
            users and a token hasn't been associated with the user              
      # parameters:
      #   hidden: true
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              example: |
                {}
      responses:
        200:
          description: Successful Response
          content: 
            text/plain:
              schema:
                $ref: '#/components/schemas/OK/text_plain'
              examples:
                'HS256 Encode':
                  value: |
                    null
                'HS256 Decode':
                  value: |
                    null
                'RS256 Encode':
                  value: |
                    code: 200
                    null
                'RS256 Decode':
                  value: |
                    null