paths: 
  '/{path}/':
    get:
      tags:
      - Examples
      summary: Debugging
      description:
        $ref: '#/components/examples/{path}.description'
      parameters:
      - in: query
        name: data
        required: false
        schema:
          AnyValue: {}
        examples:
          'string':
            value: debug this
          'object':
            value:
              debug: this
          'array':
            value: 
            - debug
            - this
    post:
      tags:
      - Examples
      summary: Debugging
      description:
        $ref: '#/components/examples/{path}.description'
      requestBody:
        content:
          text/plain:
            schema: 
              string:
              data: object
            examples: 
              'Debug this':
                value: |
                  data: Debug this
components:
  examples:
    '{path}.description': |
      Development endpoint for debugging that prints query
      parameters or request body to the terminal. Can be used to
      debug the frontend if your browser doesn't have dev tools
      or you don't want to to navigate to another page view the
      results from `console.log()`.