paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Frequency Queries
      description: |
        [Challenge](https://www.hackerrank.com/challenges/frequency-queries/problem)
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              digits: string
            examples:
              'Example 1':
                value: |
                  queries: 
                  - [1, 1]
                  - [2, 2]
                  - [3, 2]
                  - [1, 1]
                  - [1, 1]
                  - [2, 1] 
                  - [3, 2]
              'Example 2':
                value: |
                  queries: 
                  - [3, 4]
                  - [2, 1003]
                  - [1, 16]
                  - [3, 1]
              'Example 3':
                value: |
                  queries: 
                  - [1, 3]
                  - [2, 3]
                  - [3, 2]
                  - [1, 4]
                  - [1, 5]
                  - [1, 5] 
                  - [1, 4]
                  - [3, 2]
                  - [2, 4]
                  - [3, 2]
      responses:
        200:
          description: Successful Response
          content: 
            text/plain:
              schema:
                type: string
                $ref: '#/components/schemas/OK/text_plain'
              examples:
                'Example 1':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        queries: 
                        - [1, 1]
                        - [2, 2]
                        - [3, 2]
                        - [1, 1]
                        - [1, 1]
                        - [2, 1] 
                        - [3, 2]
                      output: [0, 1]
                'Example 2':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        queries: 
                        - [3, 4]
                        - [2, 1003]
                        - [1, 16]
                        - [3, 1]
                      output: [0, 1]
                'Example 3':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        queries: 
                        - [1, 3]
                        - [2, 3]
                        - [3, 2]
                        - [1, 4]
                        - [1, 5]
                        - [1, 5] 
                        - [1, 4]
                        - [3, 2]
                        - [2, 4]
                        - [3, 2]
                      output: [0, 1, 1]
                      
