paths: 
  '/{path}/':
    post:
      tags:
      - Algorithms
      summary: Grid Conversions
      description: |
        Functions for converting `m * n`, where `m, n` are nonzero integers, 
        grids or matrices to lists, dictionaries or strings.
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              grid_list: array[array[any]] | null
              grid_dict: object
              grid_str: string
              convert_to: string
            examples:
              'List to Dict':
                value: |
                  grid_list:
                  - [1, 2, 3]
                  - [4, 5, 6]
                  convert_to: dict
              'Dict to List':
                value: |
                  grid_dict:
                    '0.0': 1
                    '0.1': 2
                    '0.2': 3
                    '1.0': 4
                    '1.1': 5
                    '1.2': 6
                  convert_to: list
              'List to Str':
                value: |
                  grid_list:
                  - [1, 2, 3]
                  - [4, 5, 6]
                  convert_to: str
              'Str to List':
                value: |
                  grid_str: 0.0,1|0.1,2|0.2,3|1.0,4|1.1,5|1.2,6
                  convert_to: list
              'Dict to Str':
                value: |
                  grid_dict:
                    "0.0": 1
                    "0.1": 2
                    "0.2": 3
                  convert_to: str
              'Str to Dict':
                value: |
                  grid_str: 0.0,1|0.1,2|0.2,3|1.0,4|1.1,5|1.2,6
                  convert_to: dict
            
      responses:
        200:
          description: Successful Response
          content: 
            text/plain:
              schema:
                $ref: '#/components/schemas/OK/text_plain'
              examples:
                'Example 1':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        input:
                          linked_list: null
                          values:
                          - 1
                          - 2
                          - 3
                          - 4
                          - 5
                        output:
                          linked_list:
                            head:
                              next_node:
                                next_node:
                                  next_node:
                                    next_node:
                                      next_node: null
                                      value: 5
                                    value: 4
                                  value: 3
                                value: 2
                              value: 1
                'Example 2':
                  value: |
                    code: 200
                    status: OK
                    data:
                      input:
                        linked_list: null
                        values: []
                      output:
                        linked_list:
                          head: None
                'Example 3':
                  value: |
                    code: 200
                    status: OK
                    data:
                      input:
                        linked_list: null
                        values:
                        - value
                      output:
                        linked_list:
                          head:
                            next_node: null
                            value: value
                'Example 4':
                  value: |
                    code: 200
                    status: OK
                    data:
                      input:
                        linked_list: null
                        values:
                        - head
                        - node_1
                        - node_2
                      output:
                        linked_list:
                          head:
                            next_node:
                              next_node:
                                next_node: null
                                value: node_2
                              value: node_1
                            value: head
                'Example 5':
                  value: |
                    code: 200
                    status: OK
                    data:
                      input:
                        linked_list:
                          head:
                            next_node:
                              next_node:
                                next_node:
                                  next_node:
                                    next_node: null
                                    value: 5
                                  value: 4
                                value: 3
                              value: 2
                            value: 1
                        values: null
                      output:
                        values:
                        - 1
                        - 2
                        - 3
                        - 4
                        - 5
                'Example 6':
                  value: |
                    code: 200
                    status: OK
                    data:
                      input:
                        linked_list:
                          head: null
                        values: null
                      output:
                        values: []
                'Example 7':
                  value: |
                    code: 200
                    status: OK
                    data:
                      input:
                        linked_list:
                          head:
                            next_node: null
                            value: value
                        values: null
                      output:
                        values:
                        - value
                'Example 8':
                  value: |
                    code: 200
                    status: OK
                    data:
                      input:
                        linked_list:
                          head:
                            next_node:
                              next_node:
                                next_node: null
                                value: node_2
                              value: node_1
                            value: head
                        values: null
                      output:
                        values:
                        - head
                        - node_1
                        - node_2