paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Yahtzee
      description: |
        [Challenge](https://www.reddit.com/r/dailyprogrammer/comments/dv0231/20191111_challenge_381_easy_yahtzee_upper_section/)
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              digits: string
            examples:
              'Example 1':
                value: |
                  dice_roll: [2, 3, 5, 5, 6]
              'Example 2':
                value: |
                  dice_roll: [1, 1, 1, 1, 3]
              'Example 3':
                value: |
                  dice_roll: [1, 1, 1, 3, 3]
              'Example 4':
                value: |
                  dice_roll: [1, 2, 3, 4, 5]
              'Example 5':
                value: |
                  dice_roll: [6, 6, 6, 6, 6]
                  
      responses:
        200:
          description: Successful Response
          content: 
            text/plain:
              schema:
                type: string
                $ref: '#/components/schemas/OK/text_plain'
              examples:
                'Example 1':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        dice_roll: [2, 3, 5, 5, 6]
                      output: 
                        upper_section_scores:
                          dice: {2: 2, 3: 3, 5: 10, 6: 6}
                          max_score: 10
                'Example 2':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        dice_roll: [1, 1, 1, 1, 3]
                      output: 
                        upper_section_scores:
                          dice: {1: 4, 3: 3}
                          max_score: 4
                'Example 3':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        dice_roll: [1, 1, 1, 3, 3]
                      output: 
                        upper_section_scores:
                          dice: {1: 3, 3: 6}
                          max_score: 6
                'Example 4':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        dice_roll: [1, 2, 3, 4, 5]
                      output: 
                        upper_section_scores:
                          dice: {1: 1, 2: 2, 3: 3, 4: 4, 5: 5}
                          max_score: 5
                'Example 5':
                  value: |
                    code: 200
                    status: OK
                    data: 
                      input:
                        dice_roll: [6, 6, 6, 6, 6]
                      output: 
                        upper_section_scores:
                          dice: {6: 30}
                          max_score: 30
                          