paths: 
  '/{path}/':
    post:
      tags:
      - Coding Challenges
      summary: Yahtzee
      description: |
        [Challenge](https://www.reddit.com/r/dailyprogrammer/comments/dv0231/20191111_challenge_381_easy_yahtzee_upper_section/)
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              dice: string
            examples:
              'Example 1':
                value: |
                  dice_roll: [2, 3, 5, 5, 6]
              'Example 2':
                value: |
                  dice_roll: [1, 1, 1, 1, 3]
              'Example 3':
                value: |
                  dice_roll: [1, 1, 1, 3, 3]
              'Example 4':
                value: |
                  dice_roll: [1, 2, 3, 4, 5]
              'Example 5':
                value: |
                  dice_roll: [6, 6, 6, 6, 6]
      responses:
        200:
          description: Success
          content: 
            text/plain:
              schema:
                type: string
                dice: array
                scores: array
                max_score: number
              examples:
                'Example 1':
                  value: |
                    dice: [2, 3, 5, 6]
                    scores: [2, 3, 10, 6]
                    max_score: 10
                'Example 2':
                  value: |
                    dice: [1, 3]
                    scores: [4, 3]
                    max_score: 4
                'Example 3':
                  value: |
                    dice: [1, 3]
                    scores: [3, 6]
                    max_score: 6
                'Example 4':
                  value: |
                    dice: [1, 2, 3, 4, 5]
                    score: [1, 2, 3, 4, 5]
                    max_score: 5
                'Example 5':
                  value: |
                    dice: [6]
                    scores: [30]
                    max_score: 30
                          