environment:
  API_HOST: ${API_HOST}
  API_HOST_WLAN0: ${API_HOST_WLAN0}
  API_ENV: ${API_ENV}
  API_PORT: ${API_PORT}
  API_RELOAD: ${API_RELOAD}
  DATA_PATH: ${DATA_PATH}
  API_WORKERS: ${API_WORKERS}
  WORKDIR: ${WORKDIR}
