openapi: 3.0.2
info:
  title: Functional API Framework
  description: |
    API that uses functions to process data
    - Component based framework where each route serves a self contained 
      application or function that is an independent, reuseable piece of code 
      (functions support API and SDK requests).
    - Makes uses of the file system to automatically build and define API; 
      can drag and drop business logic within the application layer and have
      it automatically picked up by the API.
    - Uses a single route to dynamically serve GET and POST requests; 
    - Support lazy loading (lazy evaluation) for functions/routes to improve
      efficiency, performance, and memory management
    - OpenAPI documentation can be defined independently for each application,
      and consolidated into main documentation for the API.
    - Supports functional programming and is highly extendable.
  version: 2.0.5
  contact:
    name: Olufemi Jemilohun
    url: http://www.github.com/fjemi
    email: olufemi.jemilohun@gmail.com
  license_info:
    name: Apache 2.2
    url: url
tags:
- name: Examples
  description: Example functions
- name: Algorithms
  description: Algorithms algorithms
- name: Security
  description: Functions for securing the API
- name: Wrappers
  description: Wrappers over non-standard Python libraries
- name: Coding Challenges
  description: Challenges from websites such as LeetCode, HackerRank, 
    GoogleTechDev, reddit, and other sources
- name: TODO
  description: Functions with tasks to complete
# - name: Pages
#   description: Pages or templates served from GET routes
paths:
  '/{function_path}/':
    get:
      tags: 
      - Examples
      summary: Call function and process request
      operationId: call_function.get
      parameters:
      - $ref: '#/components/parameters/Path'
      - in: query
        name: data
        required: false
        examples:
          'Ping API':
            value: null
          'Hello World':
            value:
              name: Mars
        schema:
          type: object
        description: Data for the function to process
      responses:
        200: 
          description: Success
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/OK/application_json'
              examples:
                'Ping API':
                  value:
                    ping: pong
                'Hello World':
                  value:
                    text: Hello World!
    post:
      tags:
      - Examples
      summary: Call function and process request
      operationId: call_function.post
      parameters:
      - $ref: '#/components/parameters/Path'
      requestBody:
        content:
          application/json:
            schema: 
              type: object
              additionalProperties: true
            examples: 
              'Ping API':
                value: {}
              'Hello World':
                value:
                  name: Mars
          text/plain:
            schema: 
              type: string
            examples:
              'Ping API':
                value: |
                  ping: pong
              'Hello World':
                value: |
                  name: Jupyter
          multipart/form-data: 
            schema:
              properties: 
                meta-data:
                  type: string
                  format: binary
                  example: |
                    {"file_name": "someimage.jpg", "file_size_kb": "100"}
                file:
                  type: array
                  items:
                    type: string
                    format: binary
                  example:
                  - externalValue: http://wwww.someimage.com
      responses:
        200:
          description: Success
          content: 
            application/json:
              schema:
                type: object
              examples:
                'Ping API':
                  value:
                    ping: pong
                'Hello World':
                  value:
                    text: Hello World!
            text/plain:
              schema:
                type: string
              examples:
                'Ping API': 
                  value:
                    ping: pong
                'Hello World':
                  value:
                    text: Hello World!
components:
  securitySchemes:
    bearer_authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        example_jwt:

        eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb250ZW50Ijp7ImNsaWVudCI6eyJ1c2VyX2FnZW50IjpudWxsLCJvcmlnaW4iOm51bGx9LCJ1c2VyIjp7ImlkIjoidXNlcl9pZCIsImVtYWlsIjoidXNlckBlbWFpbC5jb20iLCJmaXJzdF9uYW1lIjoiZmlyc3RfbmFtZSIsImxhc3RfbmFtZSI6Imxhc3RfbmFtZSJ9fSwiZXhwaXJhdGlvbl90aW1lIjpudWxsLCJpc3N1ZWRfYXQiOm51bGwsImlzc3VlciI6bnVsbCwic3ViamVjdCI6bnVsbCwiYXVkaWVuY2UiOm51bGwsIm5vdF9iZWZvcmUiOm51bGwsImp3dF9pZCI6bnVsbH0.qen50ectsS6wLYbld8NGlCxrOMxfaPWnamC5FEQJXd8      
  parameters:
    Path:
      in: path
      name: function_path
      schema:
        type: string
      required: True
      examples:
        'Ping API':
          value: functions.examples.ping
          summary: Ping API
        'Hello World':
          value: functions.examples.hello_world
          summary: Hello World
      description: |
        Dot delimited path to a function to call to process the request. The path starts from a folder in the working directory of the app, which is set to the environment variable `WORKDIR`, and the **main** function in the module **app.py** is returned.
  schemas:
    OK:
      text_plain:
        type: string
        schema: 
          type: string
          code: number
          status: string
          data: AnyValue
      application_json:
        type: object
        properties:
          code:
            type: integer
          data:
            type:
              AnyValue: {}
          status: 
            type: string
        example:
          text: Success
      anyOf:
      - type: object
      - type: string
    Error:
      anyOf:
      - type: string
        example: |
          code: 500
          message: Internal Server Error
      - type: object
        properties:
          code:
            type: integer
          message:
            type: string
        example:
          code: 500
          message: Internal Server Error
security:
- bearer_authorization: []
